---
sudo: false
dist: trusty
language: ruby
#cache: bundler
bundler_args: --without system_tests development
rvm: 2.4
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake spec'
env: 
-  "PUPPET_VERSION=\"~> 4.10.0\""
